## define the cuda 
cuda: 1


## data 
h5_dir: "/home/sshabani/projects/CLAM/data_BRCA/data_BRCA_regression/encoded_uni_no_normalization/h5_files"
morph_dir: "/home/sshabani/projects/CLAM/data_BRCA/test_resolution/encoded_morphs_csv"
labels_csv: "/home/sshabani/projects/CLAM/data_BRCA/preprocess/slides_with_labels_IDC_ILC_with_mag.csv"
# data_path: "data/BAlt_Expirement/precomputeOverlappedResNet"
n_classes: 2

## training 
mode: train #train #train #test
batch_size: 1 
epochs: 30 #3 #200

##optimizer 
lr: 5e-6 #4e-5
wd: 5e-3
scheduler: plateau

## model
backbone: TransMIL #TransMIL
pool: mean_median #max #max   attn
emd_dim: 1024
trans: nystrom #mamba #att #nystrom att
ppeg: norm #addaptive #norm


## ways of fusion 
simple_concat: True
base_input_dim: 1024
morph_dim: 246
