## define the cuda 
cuda: 1


## data 
h5_dir: "/home/sshabani/projects/CLAM/data_BRCA/data_BRCA_regression/encoded_uni_no_normalization/h5_files"
morph_dir: "/home/sshabani/projects/CLAM/data_BRCA/test_resolution/encoded_morphs_csv"
# morph_dir: "/home/sshabani/projects/CLAM/data_BRCA/test_resolution/encoded_global_morphs_csv"
labels_csv: "/home/sshabani/projects/CLAM/data_BRCA/preprocess/slides_with_labels_IDC_ILC_with_mag.csv"
# data_path: "data/BAlt_Expirement/precomputeOverlappedResNet"
n_classes: 2

## training 
mode: train #train #train #test
batch_size: 1 
epochs: 30 #16 #3 #200

##optimizer 
lr: 5e-6 #4e-5
wd: 5e-3
scheduler: plateau

## model
backbone: MorphMIL #TransMIL
adaptor: fno
pool: mean_median #max #max   attn
emd_dim: 512 #1024 #1024
emd_morph_dim: 512 #246 #1024
input_dim: 1536 #1073 #1024 #1270 #1270 #1270 #1024 #1536 #2048
input_morph_dim: 246 #246
trans: nystrom #mamba #att #nystrom att
ppeg: norm #addaptive #norm
aug_morph: False

## ways of fusion 
simple_concat: True #False
base_input_dim: 1024
morph_dim: 246 #246

model_branch: both #both #image
cancat_type: simple #one_to_all #simple #one_to_all

## loss 
loss_type: ce_jsd #ce #ce_jsd #ce_con #ce #jsd #jsd #ce_jsd  #ce_con
alpha_jsd: 40 #
alpha_con: 0.1

## augmetation for Jsd
aug_flag: True #True #False
aug_morph: True #True #False
